import Head from 'next/head'
import Link from 'next/link'
import Headergeral from '../components/Headergeral'
import Footergeral from '../components/Footergeral'
import NewsletterNz from '../components/NewsletterNz'

export default function Vagas() {
  return (
    <div className="page-vagas">
      <Head>
        <title>Nairuz - Quem Somos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Headergeral />

      <main>
        <section className="container-fluid" id="vagas">
          <div className="container">
            <div className="row">
              <div className="col-4">
                <div className="text-quemsomos">
                  <p>Aceleramos o crescimento dos nossos clientes no ambiente digital através de projetos completos e escaláveis. Nossos times de desenvolvimento, design, marketing, atendimento e comercial atuam de forma colaborativa para entregar os melhores resultados de forma crescente e contínua, todos os dias.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="container" id="vagas-disponiveis">
          <div className="row">
            <div className="col-12">
              <p className="title-vagas">Vagas</p>
            </div>
          </div>
          <div className="row">
            <div className="col-4">
              <div className="card">
                <h3>Vaga de<br></br><span>Inbound Marketing</span></h3>
                <h4>DISPONÍVEL ATÉ 25/12/2021</h4>
                <h5>Descrição da vaga:</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac eros molestie, venenatis mi et, rhoncus justo. Proin a orci tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <h5>Requisitos:</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac eros molestie, venenatis mi et, rhoncus justo. Proin a orci tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <button className="candidatarme-vaga" id="vaga1">Candidatar-me</button>
              </div>
            </div>
            <div className="col-4">
              <div className="card">
                <h3>Vaga de<br></br><span>Designer Junior</span></h3>
                <h4>DISPONÍVEL ATÉ 25/12/2021</h4>
                <h5>Descrição da vaga:</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac eros molestie, venenatis mi et, rhoncus justo. Proin a orci tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <h5>Requisitos:</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac eros molestie, venenatis mi et, rhoncus justo. Proin a orci tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <button className="candidatarme-vaga" id="vaga2">Candidatar-me</button>
              </div>
            </div>
            <div className="col-4">
              <div className="card">
                <h3>Vaga de<br></br><span>Atendimento</span></h3>
                <h4>DISPONÍVEL ATÉ 25/12/2021</h4>
                <h5>Descrição da vaga:</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac eros molestie, venenatis mi et, rhoncus justo. Proin a orci tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <h5>Requisitos:</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac eros molestie, venenatis mi et, rhoncus justo. Proin a orci tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <button className="candidatarme-vaga" id="vaga3">Candidatar-me</button>
              </div>
            </div>
          </div>
        </section>
        <section className="container" id="vagas-off">
          <div className="row">
            <div className="col-12">
              <div className="outras-vagas">
                <div className="title-outras-vagas">
                  <p>NÃO ENCONTROU A VAGA DESEJADA?</p>
                </div>
                <div className="text-outras-vagas">
                  <p>CADASTRE-SE NO NOSSO BANCO DE TALENTOS. ANALISAREMOS SEU PERFIL E DAREMOS PRIORIDADE NAS FUTURAS VAGAS.</p>
                </div>
                <div className="button-outras-vagas">
                  <button>Cadastrar</button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <NewsletterNz />
      </main>

      <Footergeral />
    </div>
  )
}
